["¿Qué futbolista argentino ha jugado en más mundiales?", "Diego Maradona", "Javier Mascherano", "Lionel Messi", "Gabriel Batistuta", 2]
["¿Cuántos títulos de ATP ha ganado Juan Martín del Potro?", "18", "22", "25", "20",3]
["¿En qué equipo debutó profesionalmente Juan Román Riquelme?", "River Plate", "Argentinos Juniors", "Boca Juniors", "Barcelona",2]
["¿Qué atleta argentina se convirtió en la primera mujer en ganar una medalla de oro en un Mundial de Atletismo?", "Jennifer Dahlgren", "Victoria Woodward", "María Luz Tesuri", "Noelia Martínez",4]
["¿Cuántos puntos anotó Emanuel Ginóbili en su carrera en la NBA?", "10,496", "14,043","13,001","12,572", 2]
["¿Qué jugador argentino es conocido como 'El Príncipe' en el fútbol europeo?", "Juan Sebastián Verón", "Enzo Francescoli", "Gabriel Batistuta", "Hernán Crespo", 2]
["¿Cuál es el récord de victorias consecutivas del equipo de rugby Los Pumas?","8","11","12","14",3]
["¿En qué equipo de la NBA jugó Luis Scola durante más temporadas?","Phoenix Suns","Indiana Pacers","Houston Rockets","Brooklyn Nets",3]
["¿Qué logro deportivo alcanzó Delfina Merino en el año 2017?", "Ganó el oro olímpico", "Fue nombrada mejor jugadora de la Copa del Mundo", "Se retiró del hockey", "Fue elegida mejor jugadora del mundo por la FIH", 4]
